swagger: '3.0.0'
info:
  description: ADES CA1
  version: 1.0.0
  title: ADES
  # put the contact info for your development or API team
  contact:
    email: zhengwei.20@ichat.sp.edu.sg

  license:
    name: Website URL
    url: https://lzwades.herokuapp.com

paths:
  /cart/getShoppingCart:
    post:
      summary: get shopping cart
      operationId: getShoppingCart
      description: |
        By passing in the user id, you can get your shopping cart
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: uid
        description: user unique id
        schema:
          $ref: '#/definitions/GetShoppingCart'
      - in: header
        name: token
        description: user login token
        type: string
      responses:
        200:
          description: shopping cart result
          schema:
            type: array
            items:
              $ref: '#/definitions/ShoppingCart'
        403:
          description: verify user fail
        500:
          description: Internal Server Error

  /cart/editShoppingCart:
    post:
      summary: edit shopping cart
      operationId: editShoppingCart
      description: |
        By passing in the user id and cart detail, you can edit your shopping cart
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: uid
        description: user unique id and cart
        schema: 
          $ref: '#/definitions/EditShoppingCart'
      - in: header
        name: token
        description: user login token
        type: string
      responses:
        201:
          description: shopping cart edit successful
        500:
          description: Internal Server Error

  /category/getAllCategories:
    get:
      summary: get all category to display
      operationId: getAllCategories
      description: |
        By getting the category user can see the category
      produces:
      - application/json
      responses:
        200:
          description: return all category
          schema:
            $ref: '#/definitions/Categories'
        500:
          description: Internal Server Error

  /category/countOfGame/{mainCategory}:
    get:
      summary: get the total game of the category
      operationId: countOfGame
      description: |
        Send the count of each category
      produces:
      - application/json
      parameters:
      - in: patth
        name: mainCategory
        description: main category
        type: string
        required: true
      responses:
        200:
          description: return count of game
          schema:
            $ref: '#/definitions/CountOfGame'
        500:
          description: Internal Server Error

  /game/gameDetailById/{id}:
    get:
      summary: get the game detail by id
      operationId: gameDetailId
      description: |
        Return game detail
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: game id
        type: integer
        required: true
      responses:
        200: 
          description: return game detail
          schema:
            $ref: '#/definitions/GameDetail'
        204:
          description: cant find game
        500:
          description: Internal Server Error

definitions:
  GetShoppingCart:
    type: object
    required:
    - uid
    properties:
      uid:
        type: integer
        format: int64
        example: 1820797504

  ShoppingCart:
    type: array
    items: 
      $ref: '#/definitions/ShoppingCartItem'
    
  ShoppingCartItem:
    type: object
    required: 
    - game_id
    - amount
    - g_name
    - g_description
    - g_price
    - g_discount
    - g_image
    properties:
      game_id:
        type: integer
        format: int32
        example: 1
      amount:
        type: integer
        format: int32
        example: 1
      g_name:
        type: string
        example: game name
      g_description:
        type: string
        example: description
      g_price:
        type: number
        format: NUMERIC(12,2)
        example: 10.00
      g_discount:
        type: number
        format: NUMERIC(12,2)
        example: 10.00
      g_image:
        type: string
        example: /images/game1.png

  EditShoppingCart:
    type: object
    required:
    - uid
    - cart
    properties:
      uid:
        type: integer
        format: int64
        example: 1820797504
      cart:
        type: array
        items:
          $ref: '#/definitions/CartBody'

  CartBody:
    type: object
    required:
    - amount
    - id
    properties:
      amount:
        type: integer
        format: int32
        example: 1
      id:
        type: integer
        format: int32
        example: 1
  
  Categories:
    type: object
    required:
    - categories
    properties:
      categories:
        type: array
        items:
          $ref: '#/definitions/FirstCategory'

  FirstCategory:
    type: object
    required:
    - id
    - category_name
    - parent
    properties:
      id:
        type: integer
        format: int32
        example: 1
      category_name:
        type: string
        example: Video games
      parent:
        type: array
        items:
          $ref: '#/definitions/SecondCategory'

  SecondCategory:
    type: object
    required:
    - id
    - category_name
    - fk_main
    - child
    properties:
      id:
        type: integer
        format: int32
        example: 1
      category_name:
        type: string
        example: Steam Games
      fk_main:
        type: integer
        format: int32
        example: 1
      child:
        type: array
        items:
          $ref: '#/definitions/ThirdCategory'

  ThirdCategory:
    type: object
    required:
    - id
    - fk_parent
    - category_name
    properties:
      id:
        type: integer
        format: int32
        example: 1
      fk_parent:
        type: integer
        format: int32
        example: 1
      category_name:
        type: string
        example: Action Games

  CountOfGame:
    type: object
    required:
    - count
    properties:
      count:
        type: integer
        format: int32
        example: 1

  GameDetail:
    type: object
    required:
    - game
    properties:
      game: 
        type: array
        items:
          $ref: '#/definitions/GameDetailArray'
    
  GameDetailArrat:
    type: object
    required:
    - g_id
    - g_name
    - g_description
    - g_price
    - g_image
    - g_publishdate
    - g_region
    - g_discount
    - category_name
    properties:
      g_id:
        type: integer
        format: int32
        example: 1
      g_name:
        type: string
        example: Game name
      g_description: 
        type: string
        example: description
      g_price:
        type: number
        format: NUMERIC(12,2)
        example: 10.00
      g_image: 
        type: string
        example: /images/game1.png
      g_publishdate:
        type: string
        example: 11/11/2021
      g_region:
        type: integer
        example: 1
      g_discount:
        type: number
        format: NUMERIC(12,2)
        example: 10.00
      category_name:
        type: string
        example: Steam Games



# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /lzwades/ades/1.0.0
schemes:
 - https